version: "3.8"

services:
  # --------------------------------------------
  btc_db:
    image: mongo
    restart: always
    volumes:
      - /tmp/mongo-data:/data/db
  # --------------------------------------------
  btc_service:
    build:
      context: ./service
    restart: always
    env_file:
      - ./.service.env
    environment:
      MONGO_ADDR: btc_db
    volumes:
      - ./service_logs/:/app/logs
    depends_on:
      - btc_db
  # --------------------------------------------
  btc_web:
    build:
      context: ./web
    restart: always
    environment:
      MONGO_ADDR: btc_db
    depends_on:
      - btc_db
    ports:
      - "3000:3000"
